services:
  # Redis 服务 - 用作 Celery 消息队列和缓存
  redis:
    image: redis:7-alpine
    container_name: 3dprint-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - 3dprint-network

  # 前端服务 - React + Vite + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 3dprint-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - redis
    networks:
      - 3dprint-network
    environment:
      - NODE_ENV=production

# 数据卷定义
volumes:
  redis_data:
    driver: local
    name: 3dprint-redis-data

# 网络定义
networks:
  3dprint-network:
    name: 3dprint-network
    driver: bridge
